<head>
	
	<link rel="stylesheet" href="./assets/css/timeline.css">
	<title>Twitter | Timeline</title>
</head>

<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<div>
	  		<a class="menuItem" href="/timeline">
		  		Home
		  	</a>      

		  	<a class="menuItem" href="/sair">
		  		Sair
		  	</a>
		  </div>

		  <div>
		  	<i class="fab fa-twitter"></i>
		  </div>
			
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">

					<!-- Formulário do Tweet -->
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!-- Foreach que irá percorrer cada tweet e fazer a sua listagem na timeline -->
			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>

				<div class="row tweet">
					<div class="col">
						<p>
							<strong><?= $tweet['nome'] ?></strong> 
							<small>
								<span class="text text-muted">- <?=  $tweet['data']?></span>
							</small>
						</p>

						<p><?= $tweet['tweet'] ?></p>

						<br />

						<!-- Só será exibido o botão de remover caso o tweet tenha sido feito pelo autor -->
						<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?>

							<!-- Botão de remoção de tweet -->
							<form method="post" action="/removerTweet?id=<?= $tweet['id']?>">
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger">
										<small>Remover</small>
									</button>
								</div>
							</form>

						<?php } ?>
					</div>
				</div>

			<?php } ?>

		</div>

		<!-- Procurar por outros usuários -->
		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>